# 1. Array Creation using Ones and Zeros

## 1. numpy.empty

Return a new array of given shape and type, without initializing entries.

Note: It requires the user to manually set all the values in the array, and should be used with caution.

### Example 1:

In [1]:
#Code to create empty array
import numpy as np
np.empty([2, 2])

array([[1.33511562e-306, 1.69121775e-306],
       [9.34611827e-307, 9.34601641e-307]])

## 2. numpy.zeros
Return a new array of given shape and type, filled with zeros.

### Example 1:

In [2]:
# Array of three zeros. Default dtype is float 
import numpy as np
a = np.zeros(3) 
print(a)

[0. 0. 0.]


### Example 2:

In [3]:
# Array of zeros in 3*3 shape. Default dtype is float 
import numpy as np
b = np.zeros((3, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 3. numpy.ones
Return a new array of given shape and type, filled with ones.

### Example 1:

In [4]:
#Code to create array with ones as per shape
import numpy as np
a = np.ones(3) 
print(a)

[1. 1. 1.]


### Example 2:

In [5]:
#Code to create array with ones as per 3*3 shape
import numpy as np
b = np.ones((3, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 4. numpy.eye
Return a 2-D array with ones on the diagonal and zeros elsewhere. It is also called as Diagonal matrix.

### Example 1:

In [6]:
import numpy as np
a = np.eye(2) 
print(a)


[[1. 0.]
 [0. 1.]]


### Example 2:

In [7]:
import numpy as np
a = np.eye(2) 
print(a)


[[1. 0.]
 [0. 1.]]


## 5. numpy.full
Return a new array of given shape and type, filled with fill_value.

### Example 1:

In [8]:
#Code to create array as per mentioned shape and value
import numpy as np
a = np.full((2, 4), 5)
print(a)

[[5 5 5 5]
 [5 5 5 5]]


### Example 2:

In [9]:
#Code to create array as per mentioned shape and value
import numpy as np
b = np.full((3, 2), 10)
print(b)

[[10 10]
 [10 10]
 [10 10]]


# 2. Array Creation using Numerical Range

## 1. numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range.

<b>Syntax: 

numpy.arange(start, stop, step, dtype)</b>

* start - The start of an interval. If omitted, defaults to 0
* stop  - The end of an interval (not including this number)
* step  - Spacing between values, default is 1
* dtype - Data type of resulting ndarray. If not given, data type of input is used    

### Example 1:

In [10]:
# Starts from 0 to n-1
import numpy as np
num = np.arange(5) 
print(num)

[0 1 2 3 4]


### Example 2:

In [11]:
#start, end (exclusive), step
import numpy as np
num2 = np.arange(10, 30, 2) 
print(num2)

[10 12 14 16 18 20 22 24 26 28]


### Example 3:

In [12]:
# Output in float format
import numpy as np
num3 = np.arange(5, dtype = float)
print(num3)

[0. 1. 2. 3. 4.]


### Example 4:

In [13]:
#start, end (exclusive), step , dtype
import numpy as np
num4 = np.arange(10, 30, 2, dtype = float)
print(num4)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]


## 2. numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified.

<b>Syntax: 
    
numpy.linspace(start, stop, num, endpoint, retstep, dtype)</b>

* start - The starting value of the sequence
* stop  - The end value of the sequence, included in the sequence if endpoint set to true
* num   - The number of evenly spaced samples to be generated. Default is 50
* endpoint  - If true, stop is the last value in the range
* retstep - If true, returns samples and step between the consecutive numbers
* dtype - Data type of output ndarray


### Example 1:

In [14]:
#start, end, number of points
import numpy as np
a = np.linspace(10, 30, 5) 
print(a)


[10. 15. 20. 25. 30.]


### Example 2:

In [15]:
#start, end - It will split into 50 parts
import numpy as np
b = np.linspace(10, 30) 
print(b)


[10.         10.40816327 10.81632653 11.2244898  11.63265306 12.04081633
 12.44897959 12.85714286 13.26530612 13.67346939 14.08163265 14.48979592
 14.89795918 15.30612245 15.71428571 16.12244898 16.53061224 16.93877551
 17.34693878 17.75510204 18.16326531 18.57142857 18.97959184 19.3877551
 19.79591837 20.20408163 20.6122449  21.02040816 21.42857143 21.83673469
 22.24489796 22.65306122 23.06122449 23.46938776 23.87755102 24.28571429
 24.69387755 25.10204082 25.51020408 25.91836735 26.32653061 26.73469388
 27.14285714 27.55102041 27.95918367 28.36734694 28.7755102  29.18367347
 29.59183673 30.        ]


### Example 3:

In [16]:
# start, stop, num, endpoint, retstep, dtype as Integer
import numpy as np
c = np.linspace(0, 1, 5, retstep = True) 
print(c)


(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)


## 3. numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale.

<b>Syntax: 
    
numpy.logspace(start, stop, num, endpoint, base, dtype)</b>

* start - The starting value of the sequence
* stop  - The end value of the sequence, included in the sequence if endpoint set to true
* num   - The number of evenly spaced samples to be generated. Default is 50
* endpoint  - If true, stop is the last value in the range
* base - Base of log space, default is 10
* dtype - Data type of output ndarray

### Example 1:

In [17]:
# Default base is 10 
import numpy as np 
a = np.logspace(1, 2, 5) 
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


### Example 2:

In [18]:
# Base of log space to 5 
import numpy as np 
a = np.logspace(1, 2, 5, base = 5) 
print(a)

[ 5.          7.47674391 11.18033989 16.71850762 25.        ]


# 3. Array Creation using Existing Data

## 1. numpy.asarray
It Convert the input to an array. It is useful for converting Python sequence into ndarray.

<b>Syntax: 
    
numpy.asarray(a, dtype = None, order = None)</b>

Where,
* a -  Input data, in any form that can be converted to an array. This includes lists,
     lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.
* dtype  - By default, the data-type is inferred from the input data.
* order - C (row major) or F (column major). C is default  

### Example 1:

In [19]:
# convert list to ndarray 
import numpy as np 

lst = [1,2,3,4,5] 
print(np.asarray(lst))

[1 2 3 4 5]


### Example 2:

In [20]:
# convert tuple to ndarray
import numpy as np 

tple = (1,2,3,4,5) 
print(np.asarray(tple))

[1 2 3 4 5]


### Example 3:

In [21]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5,6)] 
print(np.asarray(x))

[[1 2 3]
 [4 5 6]]


### Example 4:

In [22]:
# dtype is set as float
import numpy as np 

x = [(1,2,3),(4,5,6)] 
print(np.asarray(x, dtype = float))

[[1. 2. 3.]
 [4. 5. 6.]]


## 2. numpy.copy
Return an array copy of the given object.

<b>Syntax:
    
numpy.copy(a)</b>

Where,
* a - Input data

### Example 1:

In [23]:
#Create an array a and copy to b:
import numpy as np 

a = np.array([1, 2, 3, 4, 5])
b = np.copy(a)

print("Original Array",a)
print("Copy of an Array",b)

Original Array [1 2 3 4 5]
Copy of an Array [1 2 3 4 5]


## 3. numpy.frombuffer
Interpret a buffer as a 1-dimensional array.

<b>Syntax: 
    
numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)</b>

Where,
* buffer - An object that exposes the buffer interface.
* dtype  - Data-type of the returned array; default: float.
* count  - Number of items to read. -1 means all data in the buffer
* offset - Start re.ding the buffer from this offset (in bytes); default: 0.

### Example 1:

In [24]:
import numpy as np 
s =  b'Hello' 
print(np.frombuffer(s, dtype = 'S1'))

[b'H' b'e' b'l' b'l' b'o']


## 4. numpy.fromiter
Create a new 1-dimensional array from an iterable object.

<b>Syntax:
    
numpy.fromiter(iterable, dtype, count=-1)</b>

Where,
* iterable - An iterable object providing data for the array.
* dtype - The data-type of the returned array.
* count - The number of items to read from iterable. The default is -1, which means all data is read

### Example 1:

In [25]:
# code to create array using list 
import numpy as np 

iterable = (range(10))
print(np.fromiter(iterable, int))

[0 1 2 3 4 5 6 7 8 9]


### Example 2:

In [26]:
# code to create array for square of mentioned range
import numpy as np 

iterable = (x*x for x in range(10))
print(np.fromiter(iterable, float))

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


## 5. numpy.fromstring
A new 1-D array initialized from text data in a string

<b>Syntax:
    
numpy.fromstring(string, dtype=float, count=-1, sep='')</b>

Where,
* string  - A string containing the data
* dtype   - The data type of the array; default: float
* count   - Read this number of dtype elements from the data. If this is negative (the default), the count will be determined from the length of the data.
* sep     - The string separating numbers in the data; extra whitespace between elements is also ignored

### Example 1:

In [27]:
# Code to create array from string 
import numpy as np 
strVal =  '1 2 3 4 5'
print(np.fromstring(strVal, dtype=int, sep=' '))

[1 2 3 4 5]


### Example 2:

In [28]:
# Code to create array from string 
import numpy as np 
strVal =  '1234 2343 3223'
print(np.fromstring(strVal, dtype=int, sep=' '))

[1234 2343 3223]
