# NumPy DataTypes
NumPy supports a much greater variety of numerical types than Python does

## Agenda: 
1. Numerical Data Types.
2. Usage of Data Types
3. String Data Types

Reference Link : **https://numpy.org/devdocs/user/basics.types.html**

## Numerial Data Types
1. Boolean  - 	Boolean (True or False) stored as a byte 


2. Integer  -   Number(10, 20 , -15, etc) without decimal point. Range varies between -ve and +ve range  

    Eg: np.int32 : Integer (-2147483648 to 2147483647)
    

3. Unsigned Integer - Number without decimal point. Range varies between 0 and +ve range (0 , 10 , 15 etc)
  
   Eg: np.uint32 : Unsigned integer (0 to 4294967295) 
   
   
4. Float - Number with decimal point. ( 3.14 , 3.33333333 , etc) 

   Eg: np.float32 : Here number represent the precision of the decimal point 
   
   
5. Complex - Number consists of both real and imaginary value - Complex Number ( 2 + 3j ) 

    Eg: np.complex64 -  Here number represent the complex number where real and imaginary part shares 32bits each

In [1]:
import numpy as np

### 1. Interger

In [2]:
a = np.arange(5)
print(a)
print(a.dtype)

[0 1 2 3 4]
int32


### 2. Float

In [3]:
b = np.ones((3, 3))
print(b)
print(b.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


Note: The default data type is float for zeros and ones function

### Explicity mentioning the dtype

In [4]:
a = np.arange(5, dtype='float32')
a

array([0., 1., 2., 3., 4.], dtype=float32)

In [5]:
b = np.ones((3, 3), dtype = np.int16)
print(a)
print(a.dtype)

[0. 1. 2. 3. 4.]
float32


### 3. Unsigned Integer
It will not accept -ve values

In [6]:
c = np.array([1.5,-2,3], dtype= np.uint16)
print(c)
print(c.dtype)

[    1 65534     3]
uint16


### 4. Boolean 

In [7]:
d = np.array([True, False, True])

print(d.dtype)

bool


### 5. Complex

In [8]:
e = np.array([2+3j, 2-3j]) 
print(e.dtype)

complex128


## Data Type Usage 

### 1. It can be used as Function

In [9]:
a = np.arange(5)
print(a)
print(a.dtype)

b = np.float32(a)
print(b)
print(b.dtype)

[0 1 2 3 4]
int32
[0. 1. 2. 3. 4.]
float32


### 2. Type of array can be changed using .astype() method

In [10]:
a = np.arange(5)
print(a)
b = a.astype(float)
print(b)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


### 3. It can also be referred as Character Code 

In [11]:
b = np.ones((3, 3), dtype = 'i')
print(a)
print(a.dtype)

[0 1 2 3 4]
int32


**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

### String Data Type

In [12]:
x = np.array(['V', 'A', 'P'])
print(x.dtype)

<U1


In [14]:
y = np.array(['Vinoth', 'Anand', 'Pranav'],dtype='S')
print(y.dtype)

|S6
