# NumPy - Arithmetic Operations

## Matrix Operation with Scalar

In [1]:
import numpy as np

# Creating 3*3 matrix
m1 = np.array([[10,20,30],[5,15,25],[0,5,10]])
print("Matrix is created\n",m1)

Matrix is created
 [[10 20 30]
 [ 5 15 25]
 [ 0  5 10]]


### 1 . Scalar Addition

In [2]:
a = 10 
print("Matrix is created\n",m1)
print("Scalar Addition \n", m1 + a)

Matrix is created
 [[10 20 30]
 [ 5 15 25]
 [ 0  5 10]]
Scalar Addition 
 [[20 30 40]
 [15 25 35]
 [10 15 20]]


### 2. Scalar Subtraction

In [3]:
a = 10 
print("Matrix is created\n",m1)
print("Scalar Subtraction \n", m1 - a)

Matrix is created
 [[10 20 30]
 [ 5 15 25]
 [ 0  5 10]]
Scalar Subtraction 
 [[  0  10  20]
 [ -5   5  15]
 [-10  -5   0]]


### 3. Scalar Division

In [4]:
a = 3
print("Matrix is created\n",m1)
print("Scalar Division \n", m1/a)

Matrix is created
 [[10 20 30]
 [ 5 15 25]
 [ 0  5 10]]
Scalar Division 
 [[ 3.33333333  6.66666667 10.        ]
 [ 1.66666667  5.          8.33333333]
 [ 0.          1.66666667  3.33333333]]


### 4. Scalar Multiplication

In [5]:
a = 10
print("Matrix is created\n",m1)
print("Scalar Multiplication \n", m1*a)

Matrix is created
 [[10 20 30]
 [ 5 15 25]
 [ 0  5 10]]
Scalar Multiplication 
 [[100 200 300]
 [ 50 150 250]
 [  0  50 100]]


### Element wise operations

<b>Rule:
* For matrix addition, subtraction, multiplication and division, both the matrix must be in same dimension (i.e) Same number of rows and columns</b>
    
### 1. Matrix Addition

In [6]:
import numpy as np
m1 = np.array([[10,20,30],[25,50,100],[20,40,60]])
m2 = np.array([[5,10,15],[1,50,100],[25,50,75]])

In [7]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)

First Matrix is
 [[ 10  20  30]
 [ 25  50 100]
 [ 20  40  60]]
Second Matrix is
 [[  5  10  15]
 [  1  50 100]
 [ 25  50  75]]


In [8]:
print("Addition of two matrix =\n",m1+m2)

Addition of two matrix =
 [[ 15  30  45]
 [ 26 100 200]
 [ 45  90 135]]


In [9]:
print("Addition of two matrix =\n",np.add(m1,m2))

Addition of two matrix =
 [[ 15  30  45]
 [ 26 100 200]
 [ 45  90 135]]


### 2. Matrix Subtraction

In [10]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)
print("Subtraction of two matrix =\n",m1-m2)

First Matrix is
 [[ 10  20  30]
 [ 25  50 100]
 [ 20  40  60]]
Second Matrix is
 [[  5  10  15]
 [  1  50 100]
 [ 25  50  75]]
Subtraction of two matrix =
 [[  5  10  15]
 [ 24   0   0]
 [ -5 -10 -15]]


In [11]:
print("Subtraction of two matrix =\n",np.subtract(m1,m2))

Subtraction of two matrix =
 [[  5  10  15]
 [ 24   0   0]
 [ -5 -10 -15]]


### 3. Matrix Division

In [12]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)
print("Division of two matrix =\n",m1/m2)

First Matrix is
 [[ 10  20  30]
 [ 25  50 100]
 [ 20  40  60]]
Second Matrix is
 [[  5  10  15]
 [  1  50 100]
 [ 25  50  75]]
Division of two matrix =
 [[ 2.   2.   2. ]
 [25.   1.   1. ]
 [ 0.8  0.8  0.8]]


In [13]:
print("Division of two matrix =\n",np.divide(m1,m2))

Division of two matrix =
 [[ 2.   2.   2. ]
 [25.   1.   1. ]
 [ 0.8  0.8  0.8]]


### 4. Matrix Multiplication

In [14]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)
print("Multiplication of two matrix =\n",m1*m2)

First Matrix is
 [[ 10  20  30]
 [ 25  50 100]
 [ 20  40  60]]
Second Matrix is
 [[  5  10  15]
 [  1  50 100]
 [ 25  50  75]]
Multiplication of two matrix =
 [[   50   200   450]
 [   25  2500 10000]
 [  500  2000  4500]]


In [15]:
print("Matrix Multiplication is \n", np.multiply(m1,m2))

Matrix Multiplication is 
 [[   50   200   450]
 [   25  2500 10000]
 [  500  2000  4500]]
