## Difference Between Basic and Advanced Indexing
### Basic Indexing

1. Use index number(Integer) or slicing object to access the elements.

2. The output displayed will be VIEW of the array

### Advanced Indexing

1. Accessing Methods:
    * An ndarray of type integer or boolean
    * Tuple with atleast one sequence object
    * Non tuple sequence object


2. Advanced indexing returns a copy of data rather than a view of it. 

## Types of Advanced Indexing

1. Integer Indexing 
2. Boolean Indexing 

## 1. Integer Indexing 

In [1]:
#importing the numpy library
import numpy as np

In [2]:
#Array creation 
a = np.arange(10,30,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [3]:
# Creating the array of Index
index = np.array([0,3,7])
a[index]

array([10, 16, 24])

In [4]:
# Alternative way - using list as Index
a[[0,3,7]]

array([10, 16, 24])

In [5]:
# Creating nd-arrays
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Row index of selected number, column index of selected number
b[[0,2],[0,0]]

array([1, 7])

In [7]:
# Accessing diagonal matrix values
b[[0,1,2],[0,1,2]]

array([1, 5, 9])

## 2. Boolean Indexing 
Using boolean expression as indexing

In [8]:
c = np.arange(10,100,5)
c

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [9]:
# Boolean condition for each elements of array
c>49

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
# Display the values which satisfy the boolean conditions
c[c>49]

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

### Logical And

In [11]:
# Array creation
num = np.arange(0,101,10)
print(num)

# Logical And conditions
Bgrade = np.logical_and(num>35,num<=60)

# Display the values which satisfy the boolean condition
num[Bgrade]

[  0  10  20  30  40  50  60  70  80  90 100]


array([40, 50, 60])

### Where Condition

In [12]:
# Where condition
val = np.where(num>30, num, 'NA')

# Replace the element with mentioned values for false condition
val

array(['NA', 'NA', 'NA', 'NA', '40', '50', '60', '70', '80', '90', '100'],
      dtype='<U11')