# NumPy - Statistical Functions

## Agenda:
1. Mean
2. Median
3. Standard deviation
4. Variance
5. Average

Reference Link : https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html    

## Statistics Function

In [1]:
import numpy as np

### 1. mean
Arithmetic mean is the sum of elements along an axis divided by the number of elements. The numpy.mean() function returns the arithmetic mean of elements in the array. If the axis is mentioned, it is calculated along it.

In [2]:
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

print("Mean of the Array is ", np.mean(a) )

Input Array is 
 [[14  2 11]
 [ 8  5  8]
 [15  5  5]]
Mean of the Array is  8.11111111111111


### 2. mean(axis)
Returns mean of the element of the array in a particular axis.

In [3]:
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

# axis = 0 means its y axis
print("Mean of Array Elements in y axis: ", np.mean(a, axis = 0)) 

#axis = 1 means its x axis
print("Mean of Array Elements in x axix: ", np.mean(a, axis = 1)) 


Input Array is 
 [[11  7  0]
 [ 4 13  7]
 [ 1 10  7]]
Mean of Array Elements in y axis:  [ 5.33333333 10.          4.66666667]
Mean of Array Elements in x axix:  [6. 8. 6.]


### 3. median()
Median is defined as the value separating the higher half of a data sample from the lower half.

In [4]:
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

print("Mean of the Array is ", np.median(a))

Input Array is 
 [[ 8 15  2]
 [ 5  4  8]
 [ 3 15 15]]
Mean of the Array is  8.0


### 4. median(axis)
Returns median of the element of the array in a particular axis.

In [5]:
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

print("Median of Array Elements in y axis: ", np.median(a, axis = 0)) 

#axis = 1 means its x axis
print("Median of Array Elements in x axix: ", np.median(a, axis = 1)) 

Input Array is 
 [[ 0  2  5]
 [12  0 12]
 [ 4 15  0]]
Median of Array Elements in y axis:  [4. 2. 5.]
Median of Array Elements in x axix:  [ 2. 12.  4.]


### 5. Standard Deviation
Standard deviation is the square root of the average of squared deviations from mean. 

std = sqrt(mean(abs(x - x.mean())**2))

In [6]:
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

print("Standard Deviation of the Array is ", np.std(a))

Input Array is 
 [[ 8 13 10]
 [ 1 10 14]
 [13  1 10]]
Standard Deviation of the Array is  4.581228472908512


### 6. Variance
Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). In other words, the standard deviation is the square root of variance.

In [7]:
a =  np.random.randint(16, size=(3, 3))
print("Input Array is \n", a)

print("Variance of the Array is ", np.var(a))

Input Array is 
 [[14  1 13]
 [ 0  9  6]
 [ 0 10  9]]
Variance of the Array is  26.320987654320987


### 7. average()
The average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

Considering an array [5,10,15]  and corresponding weights [1,2,3], the weighted average is calculated by adding the product of the corresponding elements and dividing the sum by the sum of weights.

Weighted average = (5*1+10*2+15*3)/(1+2+3) = 70/6 = 11.6666666

In [8]:
a = np.array([5,10,15])

print("Input Array \n", a)

#Average - # this is same as mean when weight is not specified 
print("Average of the array ", np.average(a))

Input Array 
 [ 5 10 15]
Average of the array  10.0


In [9]:
# If the weight is specified 
wt = np.array([1,2,3]) 

print("Average of the array by considering the weight ", np.average(a,weights=wt))

Average of the array by considering the weight  11.666666666666666


In [10]:
# To display the sum of weights in the result
print(np.average(a,weights = wt, returned = True))

(11.666666666666666, 6.0)
