# NumPy - Mathematical Functions

## Agenda:
1. Trigonometric or Transcendental Functions
2. Exponents Functions
3. logarithms Functions
4. Aggregate Functions 
5. Miscellaneous Functions

Reference Link : https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html    

## Trigonometric or Transcendental functions
* NumPy has standard trigonometric functions which return trigonometric ratios for a given angle in radians.

* A transcendental function is an analytic function that does not satisfy a polynomial equation, in contrast to an algebraic function.

In [1]:
import numpy as np

### 1. sin(x) function 
Trigonometric sine, element-wise.

In [2]:
x = np.arange(10)
y = np.sin(x)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


### 2. cos(x) function
Cosine element-wise.

In [3]:
y = np.cos(x)
print(y)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]


### 3. tan(x) function
Compute tangent element-wise.

In [4]:
y = np.tan(x)
print(y)

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


### sin(x) function graph

In [5]:
import matplotlib.pyplot as plt
x = np.arange(0,4*np.pi,0.1)   # start,stop,step
y = np.sin(x)
plt.plot(x,y)
plt.show()

<Figure size 640x480 with 1 Axes>

## Exponents function
### 4. exp(x)
Calculate the exponential of all elements in the input array.

In [6]:
a = np.arange(1,6)
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


## logarithms functions
### 5. log(x)
Natural logarithm, element-wise.It is the inverse of the exponential function, so that log(exp(x)) = x.The natural logarithm is logarithm in base e

In [7]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


### 6. log10 
Return the base 10 logarithm of the input array, element-wise

In [8]:
print(np.log10(a))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


## Aggregate Function 
It is a function where the values of multiple rows are grouped together to form a single summary value

### 7. min 
Element-wise minimum of array elements.

In [9]:
x = np.array([1, 3, 2, 8])
print(min(x))

1


### 8. max
Element-wise maximum of array elements.

In [10]:
x = np.array([1, 3, 2, 8])
print(max(x))

8


### 9. argmin
numpy.argmin(array, axis = None, out = None) : Returns indices of the min element of the array in a particular axis.

In [11]:
array =  np.random.randint(16, size=(4, 4))
print("INPUT ARRAY : \n", array) 
# axis = 0 means its y axis
print("Indices of min element in y axis: ", np.argmin(array, axis = 0)) 

#axis = 1 means its x axis
print("Indices of min element in x axix: ", np.argmin(array, axis = 1)) 

INPUT ARRAY : 
 [[ 1 12  5  3]
 [12  5  4 15]
 [ 1  5  1 10]
 [ 4 10 12  9]]
Indices of min element in y axis:  [0 1 2 0]
Indices of min element in x axix:  [0 2 0 0]


### 10. argmax
numpy.argmax(array, axis = None, out = None) : Returns indices of the max element of the array in a particular axis.

In [12]:
array =  np.random.randint(16, size=(4, 4))
print("INPUT ARRAY : \n", array) 
# axis = 0 means its y axis
print("Indices of max element in y axis: ", np.argmax(array, axis = 0)) 

#axis = 1 means its x axis
print("Indices of max element in x axis: ", np.argmax(array, axis = 1)) 

INPUT ARRAY : 
 [[11 15  1  4]
 [ 5 15  7 13]
 [ 0 13 11  8]
 [ 6  6  1  9]]
Indices of max element in y axis:  [0 0 2 1]
Indices of max element in x axis:  [1 1 1 3]


### 11. sum
Sum of array elements of a given array.

In [13]:
a = np.arange(5)
print(a)
print("Sum of array", sum(a))

[0 1 2 3 4]
Sum of array 10


### 12. sum(axis)
Returns sum of the element of the array in a particular axis.

In [14]:
array =  np.random.randint(16, size=(4, 4))
print("INPUT ARRAY : \n", array) 

# axis = 0 means its y axis
print("Sum of Array Elements in y axis: ", np.sum(array, axis = 0)) 

#axis = 1 means its x axis
print("Sum of Array Elements in x axix: ", np.sum(array, axis = 1)) 

INPUT ARRAY : 
 [[ 6  1  1 15]
 [ 4 14  1  3]
 [ 7 11  5  8]
 [ 1  5 12 15]]
Sum of Array Elements in y axis:  [18 31 19 41]
Sum of Array Elements in x axix:  [23 22 31 33]


## Miscellaneous

### 13. sqrt
Return the positive square-root of an array, element-wise.

In [15]:
a = [1,4,9,16]
print(np.sqrt(a))

[1. 2. 3. 4.]


### 14. square
Return the element-wise square of the input.

In [16]:
a = [1,2,3,4]
print(np.square(a))

[ 1  4  9 16]
