## Agenda
1. Array Comparison Element wise
2. Array wise comparison
3. logical_or()
4. logical_and()
5. any()
6. all()
7. Asking for help

# Array Comparison 

In [1]:
import numpy as np

In [2]:
# Creating 2 arrays to compare element wise

a = np.array([1,2,3,4,5])
b = np.array([2,3,5,4,1])

## Element Wise Comparison

In [3]:
print(a==b)

[False False False  True False]


In [4]:
print(a<b)

[ True  True  True False False]


In [5]:
print(a>b)

[False False False False  True]


### Array Wise Comparison

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])
c = np.array([1, 2, 3, 4])

In [7]:
np.array_equal(a, b)

False

In [8]:
np.array_equal(a, c)

True

# Logical Operations

In [9]:
# Creating 2 array's
a = np.array([1, 1, 0, 0])
b = np.array([1, 0, 1, 0])

### logical_or() 

In [10]:
np.logical_or(a, b)

array([ True,  True,  True, False])

### logical_and()

In [11]:
np.logical_and(a, b)

array([ True, False, False, False])

### all()

In [12]:
np.all([True, True, False,True])

False

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])
c = np.array([1, 2, 3, 4])
((a <= b) & (a <= c)).all()

True

In [14]:
a = np.array([1, 2, 3, 9])
b = np.array([2, 4, 6, 8])
c = np.array([1, 2, 3, 4])
((a <= b) & (a <= c)).all()

False

### any()

In [15]:
np.any([True, False, False, False])

True

In [16]:
a = np.array([3, 5, 7, 9])
b = np.array([2, 4, 6, 8])
c = np.array([1, 2, 3, 4])
((a <= b) & (a <= c)).any()

False

In [17]:
a = np.array([3, 5, 7, 1])
b = np.array([2, 4, 6, 8])
c = np.array([1, 2, 3, 4])
((a <= b) & (a <= c)).any()

True

### Asking for Help

In [18]:
a = np.array([3, 5, 7, 1.5])
print(a)
np.info(a)

[3.  5.  7.  1.5]
class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x224fe3ed910
byteorder:  little
byteswap:  False
type: float64


In [19]:
array =  np.random.randint(16, size=(3, 3))
print(array)
print(np.info(array))

[[ 8  4 11]
 [11 10 10]
 [10  0 11]]
class:  ndarray
shape:  (3, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x224fe3ed520
byteorder:  little
byteswap:  False
type: int32
None
