# Array Shape Manipulation

## Agenda:
1. Changing Shape of Array
    * reshape()
    * ravel()
2. Transpose Operations
    * transpose()
    * swapaxes()   
3. Adding / Removing Elements
    * resize()
    * append()
    * insert()
    * delete()
4. Joining Arrays
    * concatenate()
5. Splitting Arrays
    * split()
6. Changing Dimensions
    * broadcast_to()
    * squeeze()

#### Import NumPy package

In [1]:
import numpy as np

### 1. Changing Shape of Array
### 1. reshape()
Gives a new shape to an array without changing its data.

Syntax:

<b>numpy.reshape(arr, newshape, order')</b>

Note: 
* New shape must be compatible to the original shape
* Order ='C' : Its arrange the value in the row wise ( Default Value) 
* Order = 'F': : Its arrange the value in the column wise 

#### help() method

#Execute this code for help or additional examples
help(np.reshape)

#### Array Creation

In [2]:
# Generating 9 numbers using arange function
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
# Checking the dimension , shape and size
print(a.ndim)
print(a.shape)
print(a.size)

1
(9,)
9


#### Reshaping the matrix to (3,3)

In [4]:
# Reshaping the array 'a' to 3*3 matrix
b = np.reshape(a,(3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Reshaping the matrix to (3,3) with order as 'F'

In [5]:
# Reshaping the array 'a' to 3*3 matrix with order as 'F'
b = np.reshape(a,(3,3),order='F')
print(b)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [6]:
# Checking the shape and dimension
print(b.ndim)
print(b.shape)
print(b.size)

2
(3, 3)
9


Note: Have to mention the shape exactly matching the size of the array

#### Negative Scenario

In [7]:
# Negative Scenario 
c = np.reshape(a,(2,2)) # try (3,4)
print(c)

ValueError: cannot reshape array of size 9 into shape (2,2)

### 2. ravel()
This function returns a flattened one-dimensional array. The returned array will have the same type as that of the input array. The function takes one parameter.

Syntax:

<b>numpy.ravel(a, order)</b>

Note: 
* Order ='C' : Its arrange the value in the row wise ( Default Value) 
* Order = 'F': : Its arrange the value in the column wise

#### Array Creation using reshape function

In [8]:
a = np.arange(12).reshape(4,3) 
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# Checking the shape and dimension
print(a.ndim)
print(a.shape)
print(a.size)

2
(4, 3)
12


#### Flattened to one-dimensional array

In [10]:
# implementing the ravel method
b= np.ravel(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### Flattened to one-dimensional array using order 'F'

In [11]:
# implementing the ravel method with order as 'F'
b= np.ravel(a,order='F')
print(b)

[ 0  3  6  9  1  4  7 10  2  5  8 11]


In [12]:
# Checking the shape and dimension
print(b.ndim)
print(b.shape)
print(b.size)

1
(12,)
12


### 2. Transpose Operations

### 1. transpose()
This function changes shape of the array by swapping the position with the rows by columns and viz

Syntax:

<b>numpy.transpose(arr, axes)</b>

#### Array Creation using reshape function

In [13]:
# Creating the array using reshape method
a = np.arange(10).reshape(5,2) 
print(a)
print(a.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


#### Transpose of a matrix 

In [14]:
# Transpose of a matrix 
b = np.transpose(a)
print(b)
print(b.shape)

[[0 2 4 6 8]
 [1 3 5 7 9]]
(2, 5)


#### Transpose of a matrix using 'T'

In [15]:
# Another way to do transpose with letter 'T'
c = a.T
print(c)
print(c.shape)

[[0 2 4 6 8]
 [1 3 5 7 9]]
(2, 5)


### 2. swapaxes()
This function interchanges the two axes of an array

Syntax:

<b>numpy.swapaxes(arr, axis1, axis2)</b>

#### Array Creation using reshape function

In [16]:
# Creating an array
a = np.arange(12).reshape(4,3) 
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### swapaxes method

In [17]:
# swapping the axis
b = np.swapaxes(a,0,1)
print(b)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


## 3. Adding / Removing Elements

### 1. resize()
* This function returns a new array with the specified size.

it repeats the original array till the mentioned limit
the repeated copies of entries in the original are contained.

Syntax:

<b>numpy.resize(arr, shape)</b>

Where, 
* arr    - Input Array
* shape  - Shape of an array which needs to be created

#### Array Creation 

In [18]:
# Creating array using arange function
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### Example 1 : Size of new array equal than original array size

In [19]:
# Resizing the array as (3*4) shape
b = np.resize(a,(3,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Example 2 : Size of new array is less than original array size

In [20]:
# Resizing the array as (3*3) shape - size of array less than original array
c = np.resize(a,(3,3))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Example 3 : Size of new array is greater than original array size

In [21]:
# Resizing the array as (4*4) shape - size of array more than original array
d = np.resize(a,(4,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


###  2. append()
* This function append values at the end of an input array. 
* The dimensions of the append values must match with input array otherwise ValueError will be generated.
* If the axis is not mentioned , then 1D array will be craeted by appending values at the end

Syntax:

<b>numpy.append(arr, values, axis)</b>

Where,
* arr    - Exisiting Array
* values - Values to append. Must match the existing shape of array
* axis   - The axis along which to insert. If not given, the input array is flattened. 

#### Array Creation

In [22]:
# Creating an array 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


#### Example 1 : Appending elements without axis parameter

In [23]:
# Append Elements to the array - If axis not mentioned , it will append and create 1D array
np.append(a,[[10,10,10]])

array([ 1,  2,  3,  4,  5,  6, 10, 10, 10])

#### Example 2 : Appending elements row wise

In [24]:
# Append Elements to the array - Adding 2D values in row wise(axis = 0)
np.append(a,[[10,10,10]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10]])

#### Example 3 : Appending elements column wise

In [25]:
# Append Elements to the array - Adding 2D values in column wise(axis = 1)
np.append(a,[[10,10,10],[20,20,20]],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10],
       [20, 20, 20]])

###  3. insert()
* This function inserts values in the input array along the given axis and before the given index.
* If Insertion is not done in place and the function returns a new array

Syntax:

<b>numpy.insert(arr, obj, values, axis)</b>

Where,
* arr    - Input Array
* obj    - The index before which insertion is to be made
* values - Values to append. Must match the existing shape of array
* axis   - The axis along which to insert. If not given, the input array is flattened

#### Array Creation

In [26]:
# Creating an array 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


#### Example 1 : Inserting value without axis parameter at index 1( 1D array as output)

In [27]:
np.insert(a,1,[10,11,12]) 

array([ 1, 10, 11, 12,  2,  3,  4,  5,  6])

#### Example 2 : Inserting value along axis 0 at index 1

In [28]:
np.insert(a,1,[10,11,12],axis = 0) 

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6]])

#### Example 3 : Inserting value along axis 0 at index 1 using single value(broadcasting)

In [29]:
np.insert(a,1,[10],axis = 0) 

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 4,  5,  6]])

#### Example 4 : Inserting value along axis 1 at index 1

In [30]:
np.insert(a,1,[10,11],axis = 1) 

array([[ 1, 10,  2,  3],
       [ 4, 11,  5,  6]])

Note : Shape must match to avoid value error

#### Example 5 : Inserting value along axis 1 at index 1 using single value(broadcasting)

In [31]:
np.insert(a,1,[10],axis = 1) 

array([[ 1, 10,  2,  3],
       [ 4, 10,  5,  6]])

###  4. delete()
* This function returns a new array with the specified subarray deleted from the input array

Syntax:

<b>numpy.delete(arr, obj, axis)</b>

Where,
* arr    - Input Array
* obj    - Can be a slice, an integer or array of integers, indicating the subarray to be deleted from the input array
* axis   - The axis along which to delete the given subarray. If not given, arr is flattened

#### Array Creation

In [32]:
# Creating an array 
a = np.arange(12).reshape(4,3) 
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### Example 1 : Deleting value without axis parameter at index 2( 1D array as output)

In [33]:
np.delete(a,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Example 2 : Deleting value along axis 0 at index 2

In [34]:
np.delete(a,2,axis = 0) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11]])

#### Example 3 : Deleting value along axis 1 at index 2

In [35]:
np.delete(a,2,axis = 1) 

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

#### Example 4 : Deleting values using slicing 

In [36]:
# Creating the array
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
# Slicing using starting and ending index 
print(np.delete(a,np.s_[3:7]))

[ 0  1  2  7  8  9 10 11]


In [38]:
# Slicing using step 2
print(np.delete(a,np.s_[::2]))

[ 1  3  5  7  9 11]


## 4. Joining Arrays

### * concatenate()
This function is used to join two or more arrays of the same shape along a specified axis

Syntax:

<b>numpy.concatenate((arry1, arry2, ...), axis)</b>

Where,
* arry1,arry2.. - Sequence of arrays of the same type

* axis    - Axis along which arrays have to be joined. Default is 0

#### Creating two arrays with same shape and size

In [39]:
# Creating two arrays with same shape and size
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[7,8,9],[10,11,12]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


#### Concatenating two array's

In [40]:
# concatenating both a and b arrays together
np.concatenate((a,b)) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Concatenating two array's using axis parameter

In [41]:
# concatenating both a and b arrays together using axis = 1
np.concatenate((a,b),axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## 5. Splitting Arrays

### * split()
This function divides the array into subarrays along a specified axis.

Syntax:

<b>numpy.split(ary, indices_or_sections, axis)</b>

Where,
* ary    - Input array to be split

* indices_or_sections : int or 1-D array. If it is integer, indicating the number of equal sized subarrays to be created from the input array. If this parameter is a 1-D array, the entries indicate the points at which a new subarray is to be created.

* axis   - int, optional. The axis along which to split, default is 0.

#### 2D Array Creation

In [42]:
#### Array Creation
a = np.arange(12).reshape(4,3) 
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### Spliting the Array into 2 equal sized sub arrays

In [43]:
# spliting the array into 2 equal sized sub arrays
b = np.split(a,2)
print(b)

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]


#### 1D Array Creation

In [44]:
#### Array Creation 
c = np.arange(9) 
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### Spliting the Array into 3 equal sized sub arrays

In [45]:
d = np.split(c,3) 
print(d)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


#### Spliting the Array based on position

In [46]:
e = np.split(c,[2,7]) 
print(e)

[array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8])]


## 6. Changing Dimensions

### 1. broadcast_to()
Broadcasts an array to a new shape. It returns a read-only view on the original array. 

Note: The function may throw ValueError if the new shape does not comply with NumPy's broadcasting rules.

Syntax:

<b>numpy.broadcast_to(array, shape, subok)</b>

#### Array Creation using reshape method

In [47]:
#### Creating an array with shape (1,5)
a = np.arange(5).reshape(1,5) 
print(a)

[[0 1 2 3 4]]


#### Broadcasting

In [48]:
# applying the broadcast_to function
b = np.broadcast_to(a,(5,5))
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 2. squeeze()
This function removes one-dimensional entry from the shape of the given array

Syntax:

<b>numpy.squeeze(arr, axis)</b>

#### Example 1 :

In [49]:
# Creating the array using reshape method
# Array contains 3 layers, 1 rows and 3 columns.
a = np.arange(9).reshape(3,1,3) 
print(a)
print(a.shape)

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
(3, 1, 3)


In [50]:
# Squeezing the array
b = np.squeeze(a)
print(b)
print(b.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


#### Example 2:

In [51]:
# Creating the array using reshape method
# Array contains 3 layers, 1 rows and 3 columns.
c = np.arange(9).reshape(1,3,3) 
print(c)
print(c.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
(1, 3, 3)


In [52]:
# Squeezing the array
d = np.squeeze(c)
print(d)
print(d.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
